sudo: required
servies:
  - docker

before_install:
  - docker build -t psicorpgmbh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run psicorpgmbh/react-test npm test -- --coverage

after_success:
  - docker build -t psicorpgmbh/multi-client ./client
  - docker build -t psicorpgmbh/multi-nginx ./nginx
  - docker build -t psicorpgmbh/multi-server ./server
  - docker build -t psicorpgmbh/multi-worker ./worker
  # Log into the docker hub CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push psicorpgmbh/multi-client
  - docker push psicorpgmbh/multi-nginx
  - docker push psicorpgmbh/multi-server
  - docker push psicorpgmbh/multi-worker

