sudo: required
servies:
  - docker

before_install:
  - docker build -t psicorpgmbh/react-test -f ./client/Dockerfile.dev

script:
  - docker run psicorpgmbh/react-test npm test -- --coverage

after_success:
  - docker build -t psicorpgmbh/multi-client ./client
  - docker build -t psicorpgmbh/multi-nginx ./nginx
  - docker build -t psicorpgmbh/multi-server ./server
  - docker build -t psicorpgmbh/multi-worker ./worker
  # Log into the docker hub CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passwrod-stdin
  # Take those images and push them to the docker hub
  - docker push psicorpgmbh/mutlti-client
  - docker push psicorpgmbh/mutlti-nginx
  - docker push psicorpgmbh/mutlti-server
  - docker push psicorpgmbh/mutlti-worker

